#:include GUI/layouts/tests/header.kv
#:include GUI/layouts/tests/footer.kv

<TestScreen>:
    Header:

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.15
        pos_hint: {'center_y': 0.5}
        spacing: dp(20)
        padding: dp(20)

        TextField:
            id: genus
            size_hint_x: 0.2
            hint_text: 'Genus'
            write_tab: False

        TextField:
            id: singular
            write_tab: False
            size_hint_x: 0.5
            hint_text: 'Singular'

        MDLabel:
            id: translation
            size_hint_x: 0.3
            text: 'Translation'

    Footer:
        id: footer