#:include GUI/layouts/tests/header.kv
#:include GUI/layouts/tests/footer.kv

<TestScreen>:
    Header:

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.15
        pos_hint: {'center_y': 0.5}
        spacing: dp(20)
        padding: dp(20)

        TextField:
            id: inf
            size_hint_x: 0.5
            text_validate_unfocus: False
        MDLabel:
            id: translation
            size_hint_x: 0.4

    Footer:
        id: footer